### ISSUE TITLE
autocomplete for selection sets

### ISSUE THREAD

**Issue by NickyMeuleman** [prisma-labs/prisma-binding#250]
I'm following Andrew Mead's [modern GraphQL course](https://www.udemy.com/graphql-bootcamp/) and I fell in love with the autocomplete and errors inside GraphQL playground.

Using `prisma-binding` now that autocomplete is no longer there sadly.

I managed to get **autocomplete** working when choosing the query/mutation/subscription and the optional arguments for that query/mutation/subscription,
but **not for the selection set**.

✅ 	After an operation:
![code_2018-11-16_19-38-30](https://user-images.githubusercontent.com/30179461/48640611-78e03480-e9d7-11e8-8543-47970098d8ea.png)
✅ 	Inside the arguments for the operation:
![code_2018-11-16_19-41-07](https://user-images.githubusercontent.com/30179461/48640986-a7aada80-e9d8-11e8-81e1-429c0112239b.png)
❗️, but ✅ Inside the selection set (normal string):
![code_2018-11-16_19-48-31](https://user-images.githubusercontent.com/30179461/48641036-d032d480-e9d8-11e8-8dcd-d8769ee9c51d.png)
❗️ Inside the selection set (tagged template literal with graphql-tag):
![code_2018-11-16_19-47-14](https://user-images.githubusercontent.com/30179461/48641072-e771c200-e9d8-11e8-9b95-19f0e0a195c7.png)

Using https://github.com/prisma/vscode-graphql as graphQL extension for VSCode, this works great in `.graphql` and `.prisma` files.
Is there a way to get autocomplete(/errors) working inside the selection set passed to `prisma-binding`?

Thanks so much for the prisma-ecosystem, it's all pretty new to me, but wow, it's great so far!

**Comment by entrptaher** [comment]
Hello, is there any way to get the autocomplete? I think it's a blocking feature for prisma-binding to be using with `info` arguments.

**Comment by m1m6** [comment]
+1
