### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by kbrandwijk** [prisma-labs/prisma-binding#39]
The apollo-link that is created should support a proxy, based on `process.env.HTTP_PROXY` and `process.env.HTTPS_PROXY`. Will create a PR for this later.

**Comment by gaving** [comment]
I'd be interested in any updates to this, currently just getting a network error in corporate land (though it's good that the CLI supports a proxy now as per 1.7):-

> [Network error]: FetchError: request to https://eu1.prisma.sh/gavin-gilmour-9cd7a4/prisma-test/dev failed, reason: getaddrinfo ENOTFOUND eu1.prisma.sh eu1.prisma.sh:443
> Error: request to https://eu1.prisma.sh/gavin-gilmour-9cd7a4/prisma-test/dev failed, reason: getaddrinfo ENOTFOUND eu1.prisma.sh eu1.prisma.sh:443
>     at new CombinedError (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\errors.js:83:28)
>     at Object.checkResultAndHandleErrors (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\errors.js:101:15)
>     at CheckResultAndHandleErrors.transformResult (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\transforms\CheckResultAndHandleErrors.js:10:25)
>     at C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\transforms\transforms.js:19:54
>     at Array.reduce (<anonymous>)
>     at applyResultTransforms (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\transforms\transforms.js:18:23)
>     at C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:82:50
>     at step (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:32:23)
>     at Object.next (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:13:53)
>     at fulfilled (C:\gavin\projects\burn\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:4:58)
